---
title: "Regression Models"
author: "Kevin Martinez-Folgar"
date: "10/03/2023"
output: word_document
editor_options: 
  chunk_output_type: inline
---
```{r}
library(tidyverse)
library(survey)
library(srvyr)
library(tableone)
library(janitor)
library(broom)
```


```{r}
## Open data
data_nhanes_1 <- readRDS("proccessed_data/data_nhanes_processsed.rds")  %>%  
                  mutate(Liver_inflammation=case_when(Liver_inflammation=="Yes" ~ 1,
                                                     Liver_inflammation=="No" ~ 0),
                        Liver_fat = case_when(Liver_fat=="Yes" ~ 1,
                                              Liver_fat=="No" ~ 0),
                        Liver_fibrosis=case_when(Liver_fibrosis=="Yes" ~ 1,
                                                 Liver_fibrosis=="No" ~ 0),
                        overall=1) %>% 
    mutate(alcohol_variable=fct_relevel(alcohol_variable,
                              "Lifetime abstainers", 
                              "Former drinkers",
                              "Moderate drinkers",
                              "Heavy drinkers"),
           bmi2= fct_relevel(bmi2, "Underweight",
                                  "Normal",
                                 "Overweight", 
                                 "Obesity"),
           education=fct_relevel(education,
                                 "Completed High school or above",
                                 "Less than high school"),
           age1=fct_relevel(age1, 
                            "20-39",
                            "40-59",
                            "60+"))
```


```{r}
## Reference groups
# Race - Non-Hispanic White, Less than 1 Waist to Hip, Education More than high school, No diabetes, No Hepatitis, 
data_nhanes_1$race <- relevel(as.factor(data_nhanes_1$race),ref ="Non-Hispanic White")
data_nhanes_1$sex <- relevel(as.factor(data_nhanes_1$sex),ref ="Male")
data_nhanes_1$age1 <- relevel(as.factor(data_nhanes_1$age1),ref ="20-39")
data_nhanes_1$poverty <- relevel(as.factor(data_nhanes_1$poverty), ref="No")
data_nhanes_1$access_healthcare <- relevel(as.factor(data_nhanes_1$access_healthcare), ref="Yes")
data_nhanes_1$education <- relevel(as.factor(data_nhanes_1$education),ref ="Completed High school or above")
#data_nhanes_1$education3 <- relevel(as.factor(data_nhanes_1$education3),ref ="Some college or above")
data_nhanes_1$bmi2 <- relevel(as.factor(data_nhanes_1$bmi2),ref ="Normal")
data_nhanes_1$waist_to_hip_cat <- relevel(as.factor(data_nhanes_1$waist_to_hip_cat), ref="Less than 1")
data_nhanes_1$diabetes <- relevel(as.factor(data_nhanes_1$diabetes),ref ="No")
data_nhanes_1$HepB_Status <- relevel(as.factor(data_nhanes_1$HepB_Status),ref ="No Hepatitis B")
data_nhanes_1$HepC <- relevel(as.factor(data_nhanes_1$HepC),ref ="No Hepatitis C")
data_nhanes_1$viral <- relevel(as.factor(data_nhanes_1$viral),ref ="No")
data_nhanes_1$alcohol_variable  <- relevel(as.factor(data_nhanes_1$alcohol_variable), ref="Lifetime abstainers")
```



```{r}
## Survey Design
nhanesDesign <- svydesign(id      = ~SDMVPSU,
                          strata  = ~SDMVSTRA,  
                          weights = ~WTMECPRP,
                          nest    = TRUE,
                          data    = data_nhanes_1)

Clean_Design <- subset(nhanesDesign, complete_case==1)
```


## Table 2: 
```{r}
reggres <- function(x, data = nhanesDesign, design = Clean_Design) {
  y <- as.formula(x)

  output <- svyglm(y,
          family = poisson(),
          data   = data,
          design = design)

  tidy(output) %>% 
    mutate(CI_down=exp(estimate-1.96*std.error),
           CI_upper=exp(estimate+1.96*std.error),
           estimate=exp(estimate)) %>% 
    select(term, estimate, CI_down, CI_upper, p.value) -> model1

return(model1)
}


prepo <- function(x){
  
  x %>% 
  mutate(estimate=formatC(estimate, format="f", digits=2),
         CI_down=formatC(CI_down, format="f", digits=2),
         CI_upper=formatC(CI_upper, format="f", digits=2)) -> model_test
  
  model_test$y <- paste0(model_test$estimate, " (", model_test$CI_down,", ",model_test$CI_upper,")")
  
  model_test %>% 
    filter(term=="raceHispanic" | 
             term=="raceNon-Hispanic Asian" | 
             term=="raceNon-Hispanic Black" |
             term=="raceOther Race") %>% 
    mutate(race = case_when(term=="raceHispanic" ~  "Hispanic",
                         term=="raceNon-Hispanic Asian" ~ "Non-Hispanic Asian",
                         term=="raceNon-Hispanic Black" ~ "Non-Hispanic Black",
                         term=="raceOther Race" ~ "Other Race")) %>% 
    dplyr::select(race, y)  -> final
  
  return(final)

  }

## Liver Fat 
model_1a <- reggres("Liver_fat  ~ race + sex + age1")

model_1b <- reggres("Liver_fat  ~ race + sex + age1 + 
                                           education + access_healthcare + poverty")

model_1c <- reggres("Liver_fat  ~ race + sex + age1 + 
                                           education + access_healthcare + poverty + 
                                           viral + waist_to_hip_cat + diabetes + alcohol_variable")

## Liver Inflammation
model_2a <- reggres("Liver_inflammation  ~ race + sex + age1")

model_2b <- reggres("Liver_inflammation  ~ race + sex + age1 + 
                                  education + access_healthcare  + poverty")

model_2c <- reggres("Liver_inflammation  ~ race + sex + age1 + 
                                  education + access_healthcare + poverty + 
                                  viral + waist_to_hip_cat + diabetes + alcohol_variable")

## Liver Fibrosis
model_3a <- reggres("Liver_fibrosis  ~ race + sex + age1")

model_3b <- reggres("Liver_fibrosis  ~ race + sex + age1 + 
                                       education + access_healthcare + poverty")

model_3c <- reggres("Liver_fibrosis  ~ race + sex + age1 + 
                                       education + access_healthcare + poverty + 
                                       viral + waist_to_hip_cat + diabetes + alcohol_variable")

prepo(model_1a) %>% rename("model_1a"="y") -> model_1a_table
prepo(model_1b) %>% rename("model_1b"="y") -> model_1b_table
prepo(model_1c) %>% rename("model_1c"="y") -> model_1c_table
prepo(model_2a) %>% rename("model_2a"="y") -> model_2a_table
prepo(model_2b) %>% rename("model_2b"="y") -> model_2b_table
prepo(model_2c) %>% rename("model_2c"="y") -> model_2c_table
prepo(model_3a) %>% rename("model_3a"="y") -> model_3a_table
prepo(model_3b) %>% rename("model_3b"="y") -> model_3b_table
prepo(model_3c) %>% rename("model_3c"="y") -> model_3c_table

#list(model_1a_table, model_1b_table, model_1c_table,
#     model_2a_table, model_2b_table, model_2c_table,
#     model_3a_table, model_3b_table, model_3c_table) %>% 
#  reduce(merge, by="race")  %>% 
#  knitr::kable()


list(model_1a_table, model_1b_table, model_1c_table,
     model_2a_table, model_2b_table, model_2c_table,
     model_3a_table, model_3b_table, model_3c_table) %>% 
  reduce(merge, by="race") %>% t() %>% 
  as.data.frame() %>% 
  row_to_names(1)  -> table3

saveRDS(table3, file = "proccessed_data/table3.rds")

table3 %>% 
  select(Hispanic, `Non-Hispanic Asian`, `Non-Hispanic Black`, `Other Race`) %>% 
  knitr::kable()
```

```{r}
table3 %>% 
  select(Hispanic, `Non-Hispanic Asian`, `Non-Hispanic Black`, `Other Race`) %>% 
  write.csv("plots_tables/table2.csv")
```


## Table 3

```{r}
exposures <- c("education", "access_healthcare", "poverty",
                      "viral", "waist_to_hip_cat", "diabetes", "alcohol_variable")

outcomes1 <- c("Liver_fat", "Liver_inflammation", "Liver_fibrosis")


map(outcomes1, function(outcome){
  t<- map(exposures, function(exposure){
    #outcome<-outcomes1[[1]];exposure<-exposures[[1]]
      t <- paste0(outcome,"~",exposure,"+ sex + age1") %>% as.formula()
      
      output <- reggres(t) %>% 
                mutate(estimate=formatC(estimate, format="f", digits=2),
                       CI_down=formatC(CI_down, format="f", digits=2),
                       CI_upper=formatC(CI_upper, format="f", digits=2))
  
      output$y <- paste0(output$estimate, " (", output$CI_down,", ",output$CI_upper,")")
  
      output %>% 
        filter(grepl(exposure, term)) %>% 
        select(term, y) %>% 
        rename(model1=y) -> model_1
      
      
      t <- paste0(outcome,"~",exposure,"+ sex + age1 + race") %>% as.formula()
      output <- reggres(t) %>% 
                mutate(estimate=formatC(estimate, format="f", digits=2),
                       CI_down=formatC(CI_down, format="f", digits=2),
                       CI_upper=formatC(CI_upper, format="f", digits=2))
      output$y <- paste0(output$estimate, " (", output$CI_down,", ",output$CI_upper,")")
      
            output %>% 
        filter(grepl(exposure, term)) %>% 
        select(term, y) %>% 
        rename(model2=y) -> model_2
            
            
        model_1 %>% 
          left_join(model_2) %>% 
          mutate(exposure=exposure, 
                 outcome=outcome)-> final
  
      return(final)
    
  })
}) -> lista_modelos1

lista_modelos1

lista_modelos1 %>% 
  reduce(bind_rows) %>% 
  ungroup() %>% 
  pivot_wider(names_from = outcome, values_from = c(model1, model2)) %>% 
  select(term,
         model1_Liver_fat,
         model1_Liver_inflammation, 
         model1_Liver_fibrosis) -> table4

table4 %>% write.csv("plots_tables/table3.csv")
table4 %>% knitr::kable()
```


```{r}
lista_modelos1 %>% 
  reduce(bind_rows) %>% 
  pivot_wider(names_from = outcome, values_from = c(model1, model2)) %>% 
  select(term,
         model2_Liver_fat,
         model2_Liver_inflammation,
         model2_Liver_fibrosis) -> table3_appendix

table3_appendix %>% write.csv("plots_tables/table3_appendix_race_adjusted.csv")
table3_appendix %>% knitr::kable()
```


BMI models -- Appendix 
## Table 2 Appendix: 
```{r}
reggres <- function(x, data = nhanesDesign, design = Clean_Design) {
  y <- as.formula(x)

  output <- svyglm(y,
          family = poisson(),
          data   = data,
          design = design)

  tidy(output) %>% 
    mutate(CI_down=exp(estimate-1.96*std.error),
           CI_upper=exp(estimate+1.96*std.error),
           estimate=exp(estimate)) %>% 
    select(term, estimate, CI_down, CI_upper, p.value) -> model1

return(model1)
}


prepo <- function(x){
  
  x %>% 
  mutate(estimate=formatC(estimate, format="f", digits=2),
         CI_down=formatC(CI_down, format="f", digits=2),
         CI_upper=formatC(CI_upper, format="f", digits=2)) -> model_test
  
  model_test$y <- paste0(model_test$estimate, " (", model_test$CI_down,", ",model_test$CI_upper,")")
  
  model_test %>% 
    filter(term=="raceHispanic" | 
             term=="raceNon-Hispanic Asian" | 
             term=="raceNon-Hispanic Black" |
             term=="raceOther Race") %>% 
    mutate(race = case_when(term=="raceHispanic" ~  "Hispanic",
                         term=="raceNon-Hispanic Asian" ~ "Non-Hispanic Asian",
                         term=="raceNon-Hispanic Black" ~ "Non-Hispanic Black",
                         term=="raceOther Race" ~ "Other Race")) %>% 
    dplyr::select(race, y)  -> final
  
  return(final)

  }

## Liver Fat 
model_1a <- reggres("Liver_fat  ~ race + sex + age1")

model_1b <- reggres("Liver_fat  ~ race + sex + age1 + 
                                           education + access_healthcare + poverty")

model_1c <- reggres("Liver_fat  ~ race + sex + age1 + 
                                           education + access_healthcare + poverty + 
                                           viral + bmi2 + diabetes + alcohol_variable")

## Liver Inflammation
model_2a <- reggres("Liver_inflammation  ~ race + sex + age1")

model_2b <- reggres("Liver_inflammation  ~ race + sex + age1 + 
                                  education + access_healthcare  + poverty")

model_2c <- reggres("Liver_inflammation  ~ race + sex + age1 + 
                                  education + access_healthcare + poverty + 
                                  viral + bmi2 + diabetes + alcohol_variable")

## Liver Fibrosis
model_3a <- reggres("Liver_fibrosis  ~ race + sex + age1")

model_3b <- reggres("Liver_fibrosis  ~ race + sex + age1 + 
                                       education + access_healthcare + poverty")

model_3c <- reggres("Liver_fibrosis  ~ race + sex + age1 + 
                                       education + access_healthcare + poverty + 
                                       viral + bmi2 + diabetes + alcohol_variable")

prepo(model_1a) %>% rename("model_1a"="y") -> model_1a_table
prepo(model_1b) %>% rename("model_1b"="y") -> model_1b_table
prepo(model_1c) %>% rename("model_1c"="y") -> model_1c_table
prepo(model_2a) %>% rename("model_2a"="y") -> model_2a_table
prepo(model_2b) %>% rename("model_2b"="y") -> model_2b_table
prepo(model_2c) %>% rename("model_2c"="y") -> model_2c_table
prepo(model_3a) %>% rename("model_3a"="y") -> model_3a_table
prepo(model_3b) %>% rename("model_3b"="y") -> model_3b_table
prepo(model_3c) %>% rename("model_3c"="y") -> model_3c_table

#list(model_1a_table, model_1b_table, model_1c_table,
#     model_2a_table, model_2b_table, model_2c_table,
#     model_3a_table, model_3b_table, model_3c_table) %>% 
#  reduce(merge, by="race")  %>% 
#  knitr::kable()


list(model_1a_table, model_1b_table, model_1c_table,
     model_2a_table, model_2b_table, model_2c_table,
     model_3a_table, model_3b_table, model_3c_table) %>% 
  reduce(merge, by="race") %>% t() %>% 
  as.data.frame() %>% 
  row_to_names(1)  -> table3

saveRDS(table3, file = "proccessed_data/table3_appendix.rds")

table3 %>% 
  select(Hispanic, `Non-Hispanic Asian`, `Non-Hispanic Black`, `Other Race`) %>% 
  knitr::kable()
```

```{r}
table3 %>% 
  select(Hispanic, `Non-Hispanic Asian`, `Non-Hispanic Black`, `Other Race`) %>% 
  write.csv("plots_tables/table2_appendix.csv")
```

Waist to Hip Ratio models -- Appendix 
## Table 3 Appendix: 

```{r}
Clean_Design <- subset(nhanesDesign, complete_case==1 & waist_to_hip_valid==1)
```


```{r}
## Table 3
exposures <- c("education", "access_healthcare", "poverty",
                      "viral", "bmi2", "diabetes", "alcohol_variable")

outcomes1 <- c("Liver_fat", "Liver_inflammation", "Liver_fibrosis")


map(outcomes1, function(outcome){
  t<- map(exposures, function(exposure){
    #outcome<-outcomes1[[1]];exposure<-exposures[[1]]
      t <- paste0(outcome,"~",exposure,"+ sex + age1") %>% as.formula()
      
      output <- reggres(t) %>% 
                mutate(estimate=formatC(estimate, format="f", digits=2),
                       CI_down=formatC(CI_down, format="f", digits=2),
                       CI_upper=formatC(CI_upper, format="f", digits=2))
  
      output$y <- paste0(output$estimate, " (", output$CI_down,", ",output$CI_upper,")")
  
      output %>% 
        filter(grepl(exposure, term)) %>% 
        select(term, y) %>% 
        rename(model1=y) -> model_1
      
      
      t <- paste0(outcome,"~",exposure,"+ sex + age1 + race") %>% as.formula()
      output <- reggres(t) %>% 
                mutate(estimate=formatC(estimate, format="f", digits=2),
                       CI_down=formatC(CI_down, format="f", digits=2),
                       CI_upper=formatC(CI_upper, format="f", digits=2))
      output$y <- paste0(output$estimate, " (", output$CI_down,", ",output$CI_upper,")")
      
            output %>% 
        filter(grepl(exposure, term)) %>% 
        select(term, y) %>% 
        rename(model2=y) -> model_2
            
            
        model_1 %>% 
          left_join(model_2) %>% 
          mutate(exposure=exposure, 
                 outcome=outcome)-> final
  
      return(final)
    
  })
}) -> lista_modelos1

lista_modelos1

lista_modelos1 %>% 
  reduce(bind_rows) %>% 
  ungroup() %>% 
  pivot_wider(names_from = outcome, values_from = c(model1, model2)) %>% 
  select(term,
         model1_Liver_fat,
         model1_Liver_inflammation, 
         model1_Liver_fibrosis) -> table4

table4 %>% write.csv("plots_tables/table3_appendix.csv")
table4 %>% knitr::kable()
```



```{r}
#exposures <- c("education", 
#               "access_healthcare", 
#               "poverty",
#               "viral", 
#               "bmi2", 
#               "diabetes", 
#               "alcohol_variable")
#
#outcomes1 <- c("Liver_inflammation", "Liver_fat", "Liver_fibrosis")
#
#map(outcomes1, function(outcome){
#  t<- map(exposures, function(exposure){
#      y <- paste0(outcome,"~",exposure,"+ sex + age1 + race") %>% as.formula()
#      svyglm(y,
#          family = quasipoisson(),
#          design = Clean_Design) -> model1
#  
#      y <- paste0(outcome,"~ sex + age1 +",exposure,"*race") %>% as.formula()
#      
#     svyglm(y,
#          family = quasipoisson(),
#          design = Clean_Design) -> model2
#            
#     
#    return(list(model1=model1, model2=model2, outcome=outcome, exposure=exposure))
#    
#  })
#}) -> lista_modelos2
#
##convergence<-map_dfr(lista_modelos2, function(lista){
##  map_dfr(lista, function(temp){
##          #temp<-lista_modelos2[[1]][[1]]
##          inf1<-tidy(temp$model1) %>% pull(std.error) %>% is.infinite() %>% sum
##          inf2<-tidy(temp$model2) %>% pull(std.error) %>% is.infinite() %>% sum
##          data.frame(exposure=temp$exposure, outcome=temp$outcome,
##                     inf1=inf1, inf2=inf2)
##        })
##}) %>% 
##  filter(inf1>0|inf2>0)
##convergence
#
#
## issues in the three outcomes with alcohol_variable
## comparison: is int stat signf?
#int_sign<-map_dfr(lista_modelos2, function(lista){
#  map_dfr(lista, function(temp){
#          #temp<-lista_modelos2[[2]][[3]]
#        lrt<-tryCatch(expr= {anova(temp$model1, temp$model2)},error= function(x) NA)
#    if (is.na(lrt)){
#      pval<-NA
#    } else {
#      pval<-lrt$p
#    }
#          data.frame(exposure=temp$exposure, outcome=temp$outcome,pval=pval)
#        })
#}) %>% 
#  mutate(pval=ifelse(pval<0.001, "<0.001", format(pval, digits=3, nsmall=3))) %>% 
#  pivot_wider(id_cols=exposure, names_from=outcome, values_from=pval)
#int_sign
#
#
#lista_modelos1 %>% 
#  reduce(bind_rows) #%>% 
#  pivot_wider(term, outcome, values_from = c(model1, model2)) %>% 
#  select(term,
#         model1_Liver_fat,
#         model2_Liver_fat,
#         model1_Liver_inflammation, 
#         model2_Liver_inflammation,
#         model1_Liver_fibrosis,
#         model2_Liver_fibrosis)
```

```{r}
#
#
#svyglm(Liver_inflammation ~ sex + age1 + health_insurance*race,
#          family = quasipoisson(),
#          data   = data_nhanes_1,
#          design = Clean_Design) -> model1
#
#svyglm(Liver_inflammation ~ sex + age1 + health_insurance,
#          family = quasipoisson(),
#          data   = data_nhanes_1,
#          design = Clean_Design) -> model2
#
#anova(model1, model2) -> t1
#AIC(model1, model2)
#
```


```{r}

#svyglm("Liver_inflammation ~ alcohol_variable",family=binomial ,
#          data = nhanesDesign, design = Clean_Design) %>% summary()
#
#svyglm("Liver_inflammation ~ alcohol_variable",family=quasipoisson() ,
#          data = nhanesDesign, design = Clean_Design) %>% summary()
#
#svyglm("LUXSMED ~ alcohol_drinks_week",
#          data = nhanesDesign, design = Clean_Design) %>% summary()
#
#data_nhanes_1 %>% 
#ggplot(aes(x=alcohol_drinks_day, y=LUXSMED, color=race)) +
#  geom_point()
#
#
#data_nhanes_1 %>% 
#ggplot(aes(x=alcohol_drinks_week, y=LUXCAPM, color=race, size=WTMEC2YR)) +
#  geom_point()
#
```
